### 로그인

POST http://localhost:8080/api/auth/login
Content-Type: application/json
# Authorization: test

{
  "email": "wnsgur765z@naver.com",
  "password": "12345"
}

### 토큰 조회
GET http://localhost:8080/api/auth/me/{{userEmail}}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3bnNndXI3NjV6QG5hdmVyLmNvbSIsImlhdCI6MTY3OTIyNTAzNywiZXhwIjoxNjc5MjI1NjQyfQ.sGq8kCHNb1ApnzEaZPBlIs6h_FGAnyjmap6vsSBb_5c

